modLoader = "javafml"
loaderVersion = "*"
license = "All rights reserved"
issueTrackerURL = "https://github.com/henkelmax/corpse/issues"
[[mods]]
modId = "corpse"
version = "${mod_version}"
displayName = "Corpse"
updateJSONURL = "https://update.maxhenkel.de/neoforge/corpse"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/corpse"
logoFile = "icon.png"
authors = "Max Henkel"
description = '''
This mod brings a corpse into the game.
It will spawn upon your death containing all items that you had in your inventory.
'''
[[dependencies.corpse]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_dependency}"
ordering = "NONE"
side = "BOTH"
[[dependencies.corpse]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.21.1]"
ordering = "NONE"
side = "BOTH"
[[dependencies.corpse]]
modId = "jade"
type = "optional"
versionRange = "*"
ordering = "NONE"
side = "BOTH"
[[dependencies.corpse]]
modId = "openhud"
type = "optional"
versionRange = "${openhud_dependency}"
ordering = "AFTER"
side = "BOTH"